### ISSUE TITLE
Fails to symbolicate when loaded as a .so on android

### ISSUE THREAD

**Issue by thomcc** [rust-lang/backtrace-rs#151]
If rust code using backtrace is loaded on android as a .so, symbolication always fails, even if symbols are available.

We've also seen it cause crashes due to OOM on arm android (32 and 64 bit) in the wild (https://github.com/mozilla/application-services/issues/441, also other reports), which may or may not be related.

**Comment by thomcc** [comment]
Worth noting that on android shared object loading can be a bit weird, the object will often be loaded from inside the .apk (a zip file) directly, which [their loader supports](https://android.googlesource.com/platform/bionic/+/master/linker/linker.cpp#937).

I'm not sure if this impacts how you symbolicate though.

**Comment by alexcrichton** [comment]
This does indeed sound bad! Unfortunately though it doens't sound familiar so it'd take some effort to investigate this. I don't have a ton of time right now to look into this, but if someone has questions that I can help with I can try to do that!

**Comment by thomcc** [comment]
Do you have any advice on where you'd start digging?  E.g. Is this likely to be libbacktrace, the rust code, etc?

I don't mind looking into it, but I'm not exactly sure how all this fits together.

**Comment by kjvalencik** [comment]
I don't think this was resolved by #228. I am getting backtraces when running a `bin`, but not when loading as a shared module.

**Comment by s1341** [comment]
I have a rust binary loading a c shared library via `dlopen`. I get symbols from the rust library, but no symbols from the shared library. This is not in an 'application'. Both files are debug versions.

I'd be happy to help debug this if you can point me in the right direction?

**Comment by alexcrichton** [comment]
Can a new issue be opened for this?

The reason this doesn't work is due to android not being listed here --https://github.com/rust-lang/backtrace-rs/blob/c6e5bffdbe44cb9da250bda0a061ad5558673235/src/symbolize/gimli.rs#L362-L369 -- which means by default this crate makes no attempt to symbolize anything

**Comment by kjvalencik** [comment]
I am using `libbacktrace` to symbolize (`default-features = false, features = ["std", "libbacktrace"]`). I was able to narrow down the issue a bit.

If I set `android.defaultConfig.minSdkVersion` to `21`, it symbolizes correctly. If I set it higher, for example, to `23`, it no longer works.

**Comment by kjvalencik** [comment]
I confirmed that `HAVE_DL_ITERATE_PHDR` *is* being set. I also confirmed that the exact same `.so` works with `23`, but not `21`. It must be a runtime issue and not a compile time issue.

**Comment by alexcrichton** [comment]
Note that the detection there is not part of the gimli implementation, it may need to get ported to the gimli implementation, however. Until `dl_iterate_phdr` is called with the gimli implementation this won't work by default.

I wouldn't recommend using the libbacktrace implementation because it's likely to get removed at some point and it's historically had at least a few bugs which could lead to segfaults or worse.

**Comment by s1341** [comment]
is gimli support for `dl_iterate_phdr` imminent?

**Comment by kjvalencik** [comment]
@alexcrichton Thanks! I'll take that under advisement. For what it's the cause is Android loading the shared library directly from the apk instead of extracting it to disk during install.

https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#opening-shared-libraries-directly-from-an-apk

Setting `android:extractNativeLibs="true"` caused backtraces to start working again.

**Comment by alexcrichton** [comment]
@s1341 it needs someone to send a PR effectively.

@kjvalencik glad it works for you!

**Comment by s1341** [comment]
@alexcrichton I can take a hint! I'm not sure I'll have time for it soon though...

**Comment by kjvalencik** [comment]
@s1341 I got the ball rolling by opening a PR to `libc` to add `dl_iterate_phdr` to the Android targets (https://github.com/rust-lang/libc/pull/2144).

I have a local branch of `backtrace` confirming that it is sufficient to get backtraces working with gimli on Android.
