### ISSUE TITLE
Disable CoreSymbolication by default

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/backtrace-rs#202]
Currently it seems like coresymbolication does not work at all for me. I did not investigate it yet, but I also noticed that rust itself does not use the coresymbolication feature of this crate.

I would propose to remove it from the default features for now.

**Comment by alexcrichton** [comment]
Hm could you elaborate a bit on what's not working for you? I find that it works locally for me, albeit a little oddly. I think that the spotlight indexing service (or something like that) needs time to register the dwarf, so if I clean out a build directory for this crate and run `cargo run --example backtrace` there's no filename/line number, but after a few seconds a filename/line number shows up.

Originally this was added because libbacktrace didn't work at all or worked oddly, but nowadays libbacktrace does work for OSX more robustly. That being said it's still a giant wad of C code that has to be compiled for OSX and linked, all of which is a bummer (security vulnerabilies, more setup for compilations, etc). In that sense I don't think it's necessarily a slam dunk for disabling, but I'm curious if we could dig in to see why it's not working for you?

The standard library disables coresymbolication because they're not official APIs of OSX and we don't want to embed their usage into all Rust binaries. For crates though it seemed a reasonable default that could be explicitly disabled where necessary for distributed binaries.

**Comment by mitsuhiko** [comment]
So I notice that I no longer get filenames and line numbers from it. Not sure when it stopped working but I have not seen it in a while.

Since libraries like failure set the default features on backtrace atm you can’t opt out of coresymbolication which is annoying.

**Comment by alexcrichton** [comment]
Could... some more effort be put into learning why it stopped working? For example what calls in the code are failing? Are you seeing something like me where I have to wait for a few seconds for debuginfo to show up? Do you perhaps have spotlight turned off or something like that which may inhibit things?

It's true that turning off default features is hard, but it seemed like this was very well motivated to be added initially and "it stopped working for an unknown reason" doesn't seem like quite enough to remove it so quickly?

**Comment by mitsuhiko** [comment]
So what's happening is that it seems to hang for about 1 second, then it progresses but the `path` of the symbol coming back from code symbolication is a null pointer. The name on the other hand resolves. I will look if there is a way to build a better fallback into the code. I have not yet been able to figure out what exactly is the cause of coresymbolication not resolving here.

**Comment by alexcrichton** [comment]
Hm it's also interesting the hangs that you're experiencing, I'm not seeing those locally at all. Is there perhaps anything showing up in a profile? Or waiting for some service?

If it's this problematic I think it's definitely best to just switch to libbacktrace which should work well enough, I'm just worried that I can't reproduce the issues on my end.

**Comment by mitsuhiko** [comment]
I’m not sure how I can make this reproducible for you. It’s a mojave machine without any weird business. Drive is APFS formatted and spotlight is active.

**Comment by alexcrichton** [comment]
It turns out there's a [recent small bug](https://github.com/rust-lang/backtrace-rs/commit/adc8ab5395bb3e5b0692466a9d642d8a5467bfff) in the coresymbolication path which may fix the issue here. Can you test after that patch?

It's worth pointing out though that coresymbolication doesn't support inline frames, whereas libbacktrace does, which is a relatively major feature.

**Comment by mitsuhiko** [comment]
@alexcrichton the patch does not change anything however I found out that spotlight is to blame here. I need to run `mdimport target` for spotlight to start indexing the files. If I do that, it starts to resolve but it still takes a good second or two to do anything.

To verify I ran it on another mac which is showing the same behavior on Mojave. I wonder what is causing this.

**Comment by mitsuhiko** [comment]
My hunch is that spotlight no longer indexes dsym files placed outside of DerivedData. I just copied a new dsym there and it was instantly picked up.

**Comment by alexcrichton** [comment]
Ok I think I'm convinced that we should disable coresymbolication by default. It's always there if folks want it since it's more easily cross-compiled, but otherwise it seems like it's just not as good as libbacktrace right now.

**Comment by athre0z** [comment]
As an additional data point: I experience the same behavior as @alexcrichton where I have to wait a second before it starts working (Mojave+APFS as well). Any chance that you might have excluded your devel directory from Spotlight indexing?

**Comment by mitsuhiko** [comment]
I verified that and I didn’t. Really not clear on what this is. The dsym importer comes as part of xcode. I wonder if different versions of xcode might so that. When I’m on my mac again I can check my version of xcode.

**Comment by athre0z** [comment]
My xcode version on the 10.14.3 machine is:

```
Xcode 10.2.1
Build version 10E1001
```

Another thing that I personally experienced with Spotlight before is that the search was just clogged because it tried to index a 120 GB folder of images used as an ML training set for a few days. You notice that by the progress bar in the search window when hitting `CMD` + `space` and just typing something.

But either way, I think this whole "wait one second" thing might be annoying enough to switch the default back-end. Unfortunately, `libbacktrace` has quite some issues as well, e.g. [returning relative paths](https://github.com/ianlancetaylor/libbacktrace/issues/26) instead of absolute ones like all the other back-ends and doesn't appear to be maintained any longer. :(

**Comment by mitsuhiko** [comment]
Same version of xcode and I just validated that this also happens on a second mojave machine. However they both use the same underlying apple account and some stuff is sychronized via icloud so I wouldn't be surprised if there are some shenanigans going on.

`mdimport -L` gives me these two xcode based importers on both:

```
$ mdimport -L|grep Xcode
    "/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/Library/Spotlight/MZSpotlight.mdimporter",
    "/Applications/Xcode.app/Contents/Library/Spotlight/uuid.mdimporter",
```

If I manually `mdimport target` it resolves. Also if I copy a debug symbol into `DerivedData` it gets picked up.

**Comment by mitsuhiko** [comment]
I think all of this is a pretty good argument for pushing gimli forward :)
