### ISSUE TITLE
Line numbers are off-by-one (+1)

### ISSUE THREAD

**Issue by athre0z** [rust-lang/backtrace-rs#205]
I bisected and concluded that the issue was likely introduced in [this commit](https://github.com/rust-lang/backtrace-rs/commit/901f1f685ccde3d745fb8f3f8030d553dbb0f91d):

```
901f1f685ccde3d745fb8f3f8030d553dbb0f91d is the first bad commit
commit 901f1f685ccde3d745fb8f3f8030d553dbb0f91d
Author: Alex Crichton <alex@alexcrichton.com>
Date:   Wed May 29 08:43:51 2019 -0700

    Don't adjust the IP with libunwind

    This was first introduced with the very first implementation of
    symbolication way back when in
    rust-lang/rust@bdd31b38aaf320acc9dad5fa012ba2834348c1f8, but nowadays
    it's not entirely clear that this is still necessary. In any case it's
    best to have the adjustment done in symbolication code rather than the
    return value of `Frame::ip`, so switch to returning an unadjusted
    instruction address.

    If this causes issues we can always have some offsets later on in the
    return values!

 src/backtrace/libunwind.rs | 29 ++++-------------------------
 1 file changed, 4 insertions(+), 25 deletions(-)
```

I tested on macOS, Linux and Windows -- all platforms are affected by this issue alike.

**Edit:** On Linux, this sometimes doesn't happen, sometimes it does.
**Edit 2:** If you need something to test this with, check you can clone [this lib](https://github.com/athre0z/color-backtrace) and just run `RUST_BACKTRACE=full cargo run --example unwrap_result`.

**Comment by alexcrichton** [comment]
Wow first off that's a super cool crate, very nice!

Otherwise though here's some things I'm learning:

* For newer versions of Windows [this line](https://github.com/athre0z/color-backtrace/blob/0279be1474964e95e1bc6694b8ab7c538299c563/src/lib.rs#L493) should use `backtrace_frame` to resolve inline frames as well correctly.
* For Windows today `backtrace::resolve` fixed an off-by-one in https://github.com/rust-lang/backtrace-rs/commit/dc7dd94f2f28fcd9f83458512665c0b01cfc9ad3 which I forgot to publish
* With the master branch of this repo I can't reproduce on MinGW or MSVC
* With the latest published crate I can't reproduce with Linux. Can you expand on how to get it to spuriously trigger? After running it and rebuilding the example a bunch of times I'm not seeing a bad backtrace anywhere.
* On OSX I can see how the backtraces are a bit off and I think that the -1 logic hasn't been applied there and is a likely fix. I'm trying to figure out how to write a test for it though.

**Comment by alexcrichton** [comment]
Ok I pushed up https://github.com/rust-lang/backtrace-rs/commit/adc8ab5395bb3e5b0692466a9d642d8a5467bfff which I think fixes the issue for OSX, but I accidentally pushed it as a commit rather than a PR so I'll watch CI to make sure there's no regressions :)

**Comment by athre0z** [comment]
Thank you for the quick fix -- the code on master now works fine for me on all platforms!

On Linux, I cannot reproduce this any more either. I might have just have mixed up the terminal windows or looked wrongly, or it has a very low chance of happening.

Regarding `backtrace_frame` (I assume you meant `resolve_frame`), I just switched to the `Backtrace::new` -> `.frames()` -> `.symbols()` interface which I find somewhat more elegant than the callback based approach -- I just didn't realize it existed before. The doc of `.symbols()` sounds like this should work with inlined symbols as well, right?

**Comment by alexcrichton** [comment]
Oh oops sorry yeah I mean `resolve_frame`, but if `Backtrace::new` works that should also do the trick!
