### ISSUE TITLE
"unknown" function names on armv7-linux-androideabi, dl_iterate_phdr is not used.

### ISSUE THREAD

**Issue by artemii235** [rust-lang/backtrace-rs#227]
[Android has "dl_iterate_phdr" since API version 21](https://github.com/rust-lang/rust/issues/17520#issuecomment-344885468), but [it's explicitly disabled in backtrace-sys build.rs](https://github.com/rust-lang/backtrace-rs/blob/backtrace-sys-0.1.30/crates/backtrace-sys/build.rs#L62)
So when I run the code
```
use backtrace::Backtrace;
fn main() {
    println!("{:?}", Backtrace::new());
}
```
using `backtrace 0.3.32` I get following output:
```
stack backtrace:
   0: <unknown> (0xad95e4e8)
   1: <unknown> (0xad95e4c6)
   2: <unknown> (0xad95d7b8)
   3: <unknown> (0xad95d770)
   4: <unknown> (0xad95c718)
   5: <unknown> (0xad95c67e)
   6: <unknown> (0xad96bb22)
   7: <unknown> (0xad96c77a)
   8: <unknown> (0xad96c056)
   9: <unknown> (0xad95c670)
  10: __libc_init (0xea95978a)
```

[This commit](https://github.com/artemii235/backtrace-rs/commit/6f9ac910252ef7833105080c9cb4d5948dcb74c2) fixes the issue and I get proper backtrace, however this won't build for API versions < 21 `/target/armv7-linux-androideabi/debug/deps/libbacktrace_sys-88b2f68ba9256347.rlib(elf.o):elf.c:function __rbt_backtrace_initialize: error: undefined reference to 'dl_iterate_phdr'`. I've not submitted a PR yet as someone's build might be broken.

I wonder if this is possible to detect the used android API version and set the `build.define("HAVE_DL_ITERATE_PHDR", "1");` accordingly.
Or maybe it's fine to mention that >=21 version is only supported since it's used on [CI builds](https://github.com/rust-lang/backtrace-rs/blob/master/ci/android-ndk.sh#L19)?
Please advice.

**Comment by alexcrichton** [comment]
Thanks for the report! This definitely makes sense and probably explains https://github.com/rust-lang/backtrace-rs/issues/151 as a long-lost issue as well.

I think that we could probably fix this for this crate, but we likely can't fix it for libstd for now. That's probably better than nothing though! 

My guess as to the best fix is what you're thinking, somehow detect in the build script what the Android API version is and go from there. For the standard library we don't want to embed references to `dl_iterate_phdr` since that would change the binary compatibility and we're not quite ready to do that, but for the crate on crates.io we can customize to the toolchain we happen to find.

The **perfect** solution to this would be to update the C code to use `dlsym` to dynamically determine if `dl_iterate_phdr` is available (or somehow like that determine dynamically), but updating the C code isn't really feasible at this point. We should fix this in the `findshlibs` crate at some point, but that's a problem for later!
