### ISSUE TITLE
Line numbers requires building in debug mode?

### ISSUE THREAD

**Issue by rendaw** [rust-lang/backtrace-rs#260]
I think this would be good to document because
* How this is affected by build configurations isn't obvious at an abstract level
* The flags required to control this behavior aren't required by many other packages, and it's likely people will come here without any sort of background knowledge.

**Comment by alexcrichton** [comment]
Yes line numbers require debuginfo to be present. Debug mode isn't necessarily required, but at least `debug = 1` needs to be in `Cargo.toml`. Would be good to document!

**Comment by MeFisto94** [comment]
This could be the issue I'm seeing, if not, I'll open a different issue:
I had to downgrade backtrace-sys from 0.1.32 to 0.1.24 (32 seems current and 24 was still on my system), because with 0.1.32 lldb wouldn't show me the source code at all, it would only show the assembly.

0.1.24 on the other hand works as expected.

I was compiling servo in debug mode, does that correctly set the debug flag so it can be picked up by this crate?

**Comment by alexcrichton** [comment]
I'm going to close this because I don't think there's really a great place to document this per-se, but if folks have a location they'd check and would like to see it documented there a PR would be most welcome!
