### ISSUE TITLE
Functions in libbacktrace_sys use malloc/free/realloc directly

### ISSUE THREAD

**Issue by glandium** [rust-lang/backtrace-rs#270]
It's unfortunate that the functions in libbacktrace_sys go around the `#[global_allocator]` and uses the system allocator directly. That said, I'm not sure what those functions are used for. They don't seem to be used by the panic code.

Cc: @SimonSapin

**Comment by Mark-Simulacrum** [comment]
I've moved this over to backtrace-rs since that's where the issue would likely be fixed and reopened.

**Comment by alexcrichton** [comment]
I'm going to close this because we [use mmap where we can](https://github.com/rust-lang/backtrace-rs/blob/df444be1b325a30b4e0a1d033d500248edaf29cb/crates/backtrace-sys/build.rs#L37-L45) and otherwise modifying libbacktrace is too prohibitive. The eventual fix for this will be switching to gimli, which is all written in Rust and hence uses Rust allocation functions.
