### ISSUE TITLE
Provide a non-empty error callback to `libbacktrace`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/backtrace-rs#290]
Currently, the error callback function passed to `libbacktrace` does nothing:

https://github.com/rust-lang/backtrace-rs/blob/190b2f9bb1df384be686eadd1d14cb95de0d87d4/src/symbolize/libbacktrace.rs#L156-L158

Doing *something* here (printing an error, or just setting a flag that makes `backtrace-rs` calls fail) will make it much easier to debug issues like https://github.com/rust-lang/rust/issues/69151 - it took me quite a while to realize that the memory corruption I was seeing was the result of `libbacktrace` intentionally freeing memory.

**Comment by Aaron1011** [comment]
It will be difficult to propagate any error that we catch, since functions like `backtrace::resolve` don't use `Result`.

@alexcrichton: What do you think about making `backtrace::resolve` take an `FnMut(Result<&Symbol, SomeError>`), or return an `Result<(), SomeError>`? It would make this library somewhat less ergonomic, but it would reflect the fact that some functions are not actually infallible.

**Comment by alexcrichton** [comment]
It's currently intentional that this library pretty aggresively ignores errors. Almost all usages of this are related to debugging where an error parsing dwarf or something like that shouldn't take down other tasks.

I'm open to the idea of exposing errors somehow but I haven't really thought about how it would be done or what it would look like. There's a lot of platforms and implementations to consider here, and I'm not sure if we can usefully and efficiently communicate errors for all the platforms.

**Comment by Aaron1011** [comment]
I think communicating the *existence* of an error (even it's a ZST on some platforms) would be an enormous improvement over reporting nothing at all. This would make it much easier to debug issues like https://github.com/rust-lang/rust/issues/69151, since we'll know that something went wrong in `libbacktrace` itself.

**Comment by alexcrichton** [comment]
Er I don't mean to sound like I'm challenging the assumption that this is useful, only that implementing it "fully" may be quite difficult. Having a simple boolean bit would likely be much easier to implement and could be done relatively easily.
