### ISSUE TITLE
Please report MSRV in README and add a CI job to check compatibility

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/backtrace-rs#336]
To avoid issues like https://github.com/rust-lang/backtrace-rs/issues/335.

**Comment by alexcrichton** [comment]
There is a [job for this](https://github.com/rust-lang/backtrace-rs/blob/02bc46fa34beac05e982a109db51fb5d376c287f/.github/workflows/main.yml#L180-L189) and I personally find it too much of a hassle to put into the README, so I think having it on CI is fine.

**Comment by stevenroose** [comment]
So a Travis file names `.github/workflows/main.yml` is how you communicate your MSRV? I think that's quite disappointing for a crate as popular as backtrace-rs and for a Mozilla employee on the Rust team.

**Comment by BurntSushi** [comment]
**Moderation note:** @stevenroose That kind of personal slight against maintainers of open source projects is completely inappropriate and has no place in official Rust spaces. Please do not do it again.

If you have questions about moderation, then please email us: mods@rust-lang.org.

**Comment by stevenroose** [comment]
I didn't mean this as an ad hominem. I feel it my duty to express my concern and disappointment about the way parts of the Rust community stand towards stability. I know from experience that this is one of the arguments frequently mentioned against using Rust in production systems and a problem that our company, wiich is actually using Rust in a production system, struggles with. While our own project fully vendors all our dependencies at fixed versions, a lot of our infrastructure exists as open-source libraries. And every month or two, we notice those libraries breaking because of a package in the dependency tree disregarding an MSRV bump as a breaking semver change which ripples its way up into breaking our MSRV.

For our own projects, we think it's important to always support the Rust version on at least the last two major releases of the biggest Linux distributions. But we recognize that crates are free to decide which version they want to support. The problem is that breaking the MSRV is not considered a breaking change in the crate.

I am of course excited about the great level of innovation in the Rust ecosystem, but for a systems programming language, attention to stability is important and it's unfortunate that the lack of attention for it is not just a result of the rapid innovation of many of the third party crate maintainers but exists within the Rust team itself.

**Comment by BurntSushi** [comment]
@stevenroose This is an ecosystem level concern, and MSRV bumps requiring a semver bump has no consensus in the ecosystem. If you have ecosystem level concerns, then bringing them up in an individual's crate's issue tracker isn't the right place for it, and it's especially inappropriate to make it personal. Your "duty" doesn't trump everything else. Please don't do it again.

If you want to discuss ecosystem level concerns about this issue, then please bring them up on urlo. Inwould encourage you to search first though, because this has been discussed many times. Personally, a lot of people would be very keen to listen to a detailed production use case that is influenced by MSRV concerns.

**Comment by eminence** [comment]
I'm OK with the current policy of bumping MSRV without a corresponding semver bump, but I also would find it useful to see the current MSRV documented in the README file.
