### ISSUE TITLE
Question: How to produce a minimal binary file with backtrace-rs

### ISSUE THREAD

**Issue by joeky888** [rust-lang/backtrace-rs#413]
Hello there.

`cargo build` works, but if I compress the binary file with [upx](https://github.com/upx/upx), backtrace-rs won't print the stack trace, which means upx is out.

`cargo build --release` doesn't work, if I set the `debug = 1` under the section `[profile.release]`, it will work but the binary size will be increased by a lot.

**Comment by bjorn3** [comment]
> `cargo build --release` doesn't work, if I set the `debug = 1` under the section `[profile.release]`, it will work but the binary size will be increased by a lot.

`debug = 1` should only be necessary to get the file names, line numbers and inlined functions. Without it should still show non-inlined functions, unless you used `-Cpanic=abort`, because in that case the unwind tables are not included. These unwind tables are used for both unwinding on panics as well as unwinding to get all frames on the stack when printing a backtrace. There is not much you can do to avoid this file size increase, as the information necessary for backtraces is just big. If you can live with having to attach a debugger instead of using `RUST_BACKTRACE=1`, you could use `-Cforce-frame-pointers=1`. This slightly increases the size of the actual code and slightly decreases performance, but ensures that a debugger can unwind the stack without unwind tables.

You may have better luck by enabling LTO to shrink the code section and keep the default `-Cpanic=unwind` instead of `-Cpanic=abort`.

**Comment by joeky888** [comment]
> You may have better luck by enabling LTO to shrink the code section and keep the default -Cpanic=unwind instead of -Cpanic=abort.

Problem solved! Now I have this in the file `Cargo.toml`.
🎉 🎉 🎉 
```toml
[profile.release]
debug = 1
opt-level = "z"
lto = true
codegen-units = 1
```
🎉 🎉 🎉
