### ISSUE TITLE
v0.3.74 fails to build on Windows

### ISSUE THREAD

**Issue by KapJI** [rust-lang/backtrace-rs#676]
Here are the errors: [backtrace-errors.txt](https://github.com/user-attachments/files/17706575/backtrace-errors.txt)

We are building project with [buck2](https://github.com/facebook/buck2) but third party dependencies are resolved and vendored by cargo.

Is `windows-sys` dependency wrong?

v0.3.73 and below work fine. Other platforms seems to be ok as well.

**Comment by ChrisDenton** [comment]
We don't use the `windows-sys` crate, we use `windows-bindgen` to pre-generate our own [windows_sys.rs](https://github.com/rust-lang/backtrace-rs/blob/master/src/windows_sys.rs) module. We do have a dependency on `windows-targets` though.

The errors look like they come from our code that tries to validate the APIs are correct (aisde: this code is probably redundant now we're not hand-writing anything). This is failing for you for some reason but not for our CI (or in the rust-lang/rust repo). My guess would be you're using the windows raw dylib environment variable and that's causing a difference somewhere.

**Comment by KapJI** [comment]
I can bisect it to specific commit tomorrow.

**Comment by ChrisDenton** [comment]
Following up on my hunch it seems that the `windows-targets` crate using `extern "C"` for all ABIs on 64-bit systems when windows_raw_dylib is used https://github.com/microsoft/windows-rs/blob/a8e14c75581bb89fc244ad480f98567be972aea2/crates/libs/targets/src/lib.rs#L23C9-L23C10 which would account for the ABI mismatch assertions failing. I seem to recall there was a reason for that, but I can't quite remember. I guess it's because all the x86 ABIs just resolve to `extern "C"` on x64 and arm64.

**Comment by KapJI** [comment]
We add `windows_raw_dylib` indeed. But it was there before that as well and backtrace build was passing. What has changed with the latest release? For builds we have regular `windows-latest` Github runner.

**Comment by KapJI** [comment]
Bisected to https://github.com/rust-lang/backtrace-rs/pull/653 which added dependency of `windows-targets`.

**Comment by dtolnay** [comment]
Non-Buck repro, as of the current master branch of this repo (https://github.com/rust-lang/backtrace-rs/commit/4f3acf7a0a9f686ec004716e5d514d9732b41486):

`rustup target add x86_64-pc-windows-msvc`
`RUSTFLAGS=--cfg=windows_raw_dylib cargo check --target x86_64-pc-windows-msvc`

**Comment by ChrisDenton** [comment]
> I seem to recall there was a reason for that,

Ah jogged my memory: this was because of https://github.com/microsoft/windows-rs/pull/2458. Varargs weren't being correctly handled by rustc so this was a workaround. It's been fixed in rustc now but the MSRV of windows-related crates means it's unlikely to revert the workaround any time soon. So best thing to do would be to update our validation or remove them entirely if nobody can think of a reason why they're still needed.
